Remove numpy restriction (#762)
* allow all numpy

* psycopg2-binary

* dummy plugin config

* no simplejson

* dependency cleanup

* pre-commit

* uv in action

* try to fix tests

* Potential fix for code scanning alert no. 867: Empty except

Co-authored-by: Copilot Autofix powered by AI <62310815+github-advanced-security[bot]@users.noreply.github.com>

* test plugins

* pre commit

* test plugins

* clone plugin

* env

* env

* integral dependencies

* no export

* decouple plugins

* nb2workflow test dep extras

* integral plugin branch

* poolar plugin

* typo

* polar dep

* actually polar

* syntax

* no polar test

* uv version

* tap tests

* python versions tap test

* psycopg2 non-binary

* export full dev requirements

* requirements

* Add license information to pyproject.toml

---------

Co-authored-by: Copilot Autofix powered by AI <62310815+github-advanced-security[bot]@users.noreply.github.com>

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -21,49 +21,48 @@ jobs:
 
     strategy:
       matrix:
-        python-version: [3.8, 3.9]
+        python-version: ['3.10', '3.11', '3.12', '3.13']
 
     steps:
-    - uses: actions/checkout@v2
-    - name: Set up Python ${{ matrix.python-version }}
-      uses: actions/setup-python@v2
+    - uses: actions/checkout@v4
+
+    - name: Install uv and set the python version
+      uses: astral-sh/setup-uv@v6
       with:
+        version: "0.8.22"
         python-version: ${{ matrix.python-version }}
 
-    - name: Install dependencies
+    - name: Install the project
       run: |
-        python -m pip install --upgrade pip
-        pip install flake8 pytest mypy pylint pytest-cov pytest-xdist wheel
-        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
-        pip install -e .[test,ontology]
+        uv sync --locked --all-extras --dev
         curl -o tests/oda-ontology.ttl https://raw.githubusercontent.com/oda-hub/ontology/main/ontology.ttl
 
     - name: Lint with flake8
       if: ${{ env.TEST_ONLY_FAST != 'true' }}
       run: |
         # stop the build if there are Python syntax errors or undefined names
-        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics || echo "failed lint"
+        uv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics || echo "failed lint"
         # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
-        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics || echo "failed second lint"
+        uv run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics || echo "failed second lint"
 
     - name: PyLint - more lint
       if: ${{ env.TEST_ONLY_FAST != 'true' }}
       run: |
-        pylint -E cdci_data_analysis || echo 'this is fine!'
+        uv run pylint -E cdci_data_analysis || echo 'this is fine!'
 
     - name: MyPy
       if: ${{ env.TEST_ONLY_FAST != 'true' }}
       run: |
-        mypy cdci_data_analysis --ignore-missing-imports || echo 'this is fine too!'
+        uv run mypy cdci_data_analysis --ignore-missing-imports || echo 'this is fine too!'
 
     - name: Test fast subset with pytest
       run: |
-        python -m pytest tests --cov=cdci_data_analysis -sv --full-trace --log-cli-level=DEBUG -m "not test_drupal and fast and not test_renku and not test_matrix and not test_tap" --durations=0
+        uv run python -m pytest tests --cov=cdci_data_analysis -sv --full-trace --log-cli-level=DEBUG -m "not test_drupal and fast and not test_renku and not test_matrix and not test_tap" --durations=0
 
     - name: Test everything with pytest
       if: ${{ env.TEST_ONLY_FAST != 'true' }}
       run: |
-        python -m pytest tests --cov=cdci_data_analysis -sv --full-trace --log-cli-level=DEBUG -m "not test_drupal and not test_renku and not test_matrix and not test_tap" --durations=0
+        uv run python -m pytest tests --cov=cdci_data_analysis -sv --full-trace --log-cli-level=DEBUG -m "not test_drupal and not test_renku and not test_matrix and not test_tap" --durations=0
 
 
     # I wonder how this interacts with the Github App. But this is not only for PR. Also this does not always work
